# Generated by Django 4.2.20 on 2025-05-09 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='genders',
            table='tbl_genders',
        ),
        migrations.AlterModelTable(
            name='users',
            table='tbl_users',
        ),
    ]
